# Generated by Django 4.2.1 on 2023-06-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=45)),
                ('desc_categoria', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Categoria_material',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subcategoría', models.CharField(max_length=45)),
                ('desc_subcategoria', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Subcategoria_material',
            },
        ),
        migrations.CreateModel(
            name='Unidad_de_medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad_de_medida', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Unidad_de_medida',
            },
        ),
        migrations.CreateModel(
            name='Materia_prima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
                ('merma', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('energia', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('h_de_carbono', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('proteina', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('sodio', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('azucares', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('grasa_total', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('grasa_saturada', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('mono', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('poli', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('colesterol', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('fibra', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.categoria_material')),
                ('subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.subcategoria_material')),
                ('unidad_de_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.unidad_de_medida')),
            ],
            options={
                'verbose_name_plural': 'MMPP',
            },
        ),
    ]
