# Generated by Django 4.2.1 on 2023-06-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia_prima',
            options={'verbose_name_plural': 'Material'},
        ),
    ]
