# Generated by Django 4.2.1 on 2023-06-20 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_alter_materia_prima_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=45)),
                ('desc_categoria', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=45)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.categoria_producto')),
                ('ingredientes', models.ManyToManyField(to='recetas.materia_prima')),
            ],
            options={
                'verbose_name_plural': 'Recetas',
            },
        ),
    ]
