# Generated by Django 4.2.1 on 2023-06-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_categoria_producto_receta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia_prima',
            options={'verbose_name_plural': 'Materia Prima'},
        ),
        migrations.RenameField(
            model_name='subcategoria_material',
            old_name='nombre_subcategoría',
            new_name='nombre_subcategoria',
        ),
    ]
