# Generated by Django 4.2.1 on 2023-06-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_alter_materia_prima_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria_material',
            name='desc_subcategoria',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
