# Generated by Django 4.2.1 on 2023-06-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_alter_subcategoria_material_desc_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_material',
            name='desc_categoria',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='categoria_producto',
            name='desc_categoria',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='azucares',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='colesterol',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='energia',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='fibra',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='grasa_saturada',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='grasa_total',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='h_de_carbono',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='merma',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='mono',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='poli',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='proteina',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='sodio',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
