# Generated by Django 4.2.1 on 2023-06-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_alter_categoria_material_desc_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia_prima',
            name='merma',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Merma en %'),
        ),
    ]
