# Generated by Django 4.2.1 on 2023-06-21 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_alter_materia_prima_merma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia_prima_Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.materia_prima')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
        ),
    ]
