# Generated by Django 4.2.1 on 2023-06-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0009_remove_materia_prima_recetas_materia_prima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gramajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia_prima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
                ('merma', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Merma en %')),
                ('energia', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('h_de_carbono', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('proteina', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('sodio', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('azucares', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('grasa_total', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('grasa_saturada', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('mono', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('poli', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('colesterol', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('fibra', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.categoria_material')),
                ('subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.subcategoria_material')),
            ],
            options={
                'verbose_name_plural': 'Materia Prima',
            },
        ),
        migrations.AlterModelOptions(
            name='unidad_de_medida',
            options={'verbose_name_plural': 'Unidad_de_medida'},
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=45)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.categoria_producto')),
                ('ingredientes', models.ManyToManyField(through='recetas.Gramajes', to='recetas.materia_prima')),
            ],
            options={
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.AddField(
            model_name='materia_prima',
            name='unidad_de_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.unidad_de_medida'),
        ),
        migrations.AddField(
            model_name='gramajes',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.materia_prima'),
        ),
        migrations.AddField(
            model_name='gramajes',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta'),
        ),
        migrations.AlterUniqueTogether(
            name='gramajes',
            unique_together={('receta', 'materia_prima')},
        ),
    ]
