# Generated by Django 4.2.1 on 2023-06-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0010_gramajes_materia_prima_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria_producto',
            new_name='Categoria_receta',
        ),
        migrations.AlterModelOptions(
            name='categoria_material',
            options={'verbose_name_plural': 'Categorias material'},
        ),
        migrations.AlterModelOptions(
            name='categoria_receta',
            options={'verbose_name_plural': 'Categorias Receta'},
        ),
        migrations.AlterModelOptions(
            name='materia_prima',
            options={'verbose_name_plural': 'Materias Primas'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria_material',
            options={'verbose_name_plural': 'Subcategorias material'},
        ),
        migrations.AlterModelOptions(
            name='unidad_de_medida',
            options={'verbose_name_plural': 'Unidades de medida'},
        ),
    ]
