# Generated by Django 4.2.1 on 2023-06-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0011_rename_categoria_producto_categoria_receta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia_prima',
            old_name='energia',
            new_name='calorias',
        ),
        migrations.RenameField(
            model_name='materia_prima',
            old_name='h_de_carbono',
            new_name='carbohidratos',
        ),
        migrations.RenameField(
            model_name='materia_prima',
            old_name='fibra',
            new_name='fibras',
        ),
        migrations.RenameField(
            model_name='materia_prima',
            old_name='mono',
            new_name='grasa_monosaturada',
        ),
        migrations.RenameField(
            model_name='materia_prima',
            old_name='poli',
            new_name='grasa_poliinsaturada',
        ),
        migrations.AddField(
            model_name='materia_prima',
            name='grasa_trans',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
