# Generated by Django 4.2.1 on 2023-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0012_rename_energia_materia_prima_calorias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='producto',
            new_name='nombre_receta',
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='azucares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='calorias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='carbohidratos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='colesterol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='fibras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='grasa_monosaturada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='grasa_poliinsaturada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='grasa_saturada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='grasa_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='grasa_trans',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='merma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Merma en %'),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='proteina',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='sodio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
