# Generated by Django 4.2.1 on 2023-06-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0013_rename_producto_receta_nombre_receta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_material',
            name='nombre_categoria',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria_receta',
            name='nombre_categoria',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='materia_prima',
            name='descripcion',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre_receta',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategoria_material',
            name='nombre_subcategoria',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='unidad_de_medida',
            name='nombre_unidad_de_medida',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
