# Generated by Django 4.2.1 on 2023-06-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0015_alter_gramajes_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia_prima',
            name='inventario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
