# Generated by Django 4.2.1 on 2023-06-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0015_alter_gramajes_cantidad'),
        ('compras', '0002_alter_orden_de_compra_options_alter_q_mp_oc_nro_oc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Q_Mp_Oc',
            new_name='Mp_Oc',
        ),
    ]
