# Generated by Django 4.2.1 on 2023-06-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_rename_materia_prima_orden_de_compra_materias_primas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_OC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Sin recepción', 'Sin recepción'), ('Recepción Parcial', 'Recepción Parcial'), ('Recepcionada', 'Recepcionada')], default='Sin recepción', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='orden_de_compra',
            name='estado_oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.estado_oc'),
        ),
        migrations.AddField(
            model_name='orden_de_compra',
            name='estado_recepcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.estado_recepcion'),
        ),
    ]
