# Generated by Django 4.2.1 on 2023-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_orden_de_compra_estado_oc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_de_compra',
            name='nro_oc',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
