# Generated by Django 4.2.1 on 2023-06-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_orden_de_compra_nro_oc'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='email_oc',
            field=models.EmailField(default='test@example.com', max_length=45),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='comuna',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email_contacto_1',
            field=models.EmailField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='giro',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_contacto_1',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='region',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
