# Generated by Django 4.2.1 on 2023-06-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_proveedor_email_oc_alter_proveedor_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_de_compra',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
