# Generated by Django 4.2.1 on 2023-06-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_orden_de_compra_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_de_compra',
            name='nro_oc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
