# Generated by Django 4.2.1 on 2023-06-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recetas', '0015_alter_gramajes_cantidad'),
        ('compras', '0014_remove_orden_de_compra_materias_primas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mp_Oc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('materia_prima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.materia_prima')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=10)),
                ('condicion_de_pago', models.IntegerField(null=True)),
                ('email_oc', models.EmailField(default='test@example.com', max_length=45)),
                ('giro', models.CharField(blank=True, max_length=90, null=True)),
                ('pais', models.CharField(blank=True, max_length=45, null=True)),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=45, null=True)),
                ('comuna', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=90, null=True)),
                ('nombre_contacto_1', models.CharField(blank=True, max_length=45, null=True)),
                ('email_contacto_1', models.EmailField(blank=True, max_length=45, null=True)),
                ('telefono_contacto_1', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo_contacto_1', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre_contacto_2', models.CharField(blank=True, max_length=45, null=True)),
                ('email_contacto_2', models.EmailField(blank=True, max_length=45, null=True)),
                ('telefono_contacto_2', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo_contacto_2', models.CharField(blank=True, max_length=45, null=True)),
                ('info_adicional', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Orden_de_compra',
            fields=[
                ('nro_oc', models.AutoField(default=1000, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado_recepcion', models.CharField(choices=[('Sin recepción', 'Sin recepción'), ('Recepción Parcial', 'Recepción Parcial'), ('Recepcionada', 'Recepcionada')], default='Sin recepción', max_length=20)),
                ('estado_oc', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=20)),
                ('materias_primas', models.ManyToManyField(through='compras.Mp_Oc', to='recetas.materia_prima')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Compra',
            },
        ),
        migrations.AddField(
            model_name='mp_oc',
            name='nro_oc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.orden_de_compra'),
        ),
    ]
