# Generated by Django 4.2.1 on 2023-06-26 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0015_alter_gramajes_cantidad'),
        ('compras', '0017_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recepcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materia_prima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.materia_prima')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('nro_recepcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('estado_recepcion', models.CharField(choices=[('Sin recepción', 'Sin recepción'), ('Recepción Parcial', 'Recepción Parcial'), ('Recepcionada', 'Recepcionada')], default='Sin recepción', max_length=20)),
                ('materias_primas', models.ManyToManyField(through='compras.OcRecepcion', to='recetas.materia_prima')),
            ],
        ),
        migrations.AddField(
            model_name='ocrecepcion',
            name='nro_recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_recepcion', to='compras.recepcion'),
        ),
        migrations.AddField(
            model_name='ocrecepcion',
            name='orden_de_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc_recepcion', to='compras.orden_de_compra'),
        ),
    ]
