# Generated by Django 4.2.1 on 2023-06-26 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_ocrecepcion_recepcion_ocrecepcion_nro_recepcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recepcion',
            options={'verbose_name_plural': 'Recepciones'},
        ),
        migrations.RemoveField(
            model_name='ocrecepcion',
            name='orden_de_compra',
        ),
        migrations.AddField(
            model_name='recepcion',
            name='nro_oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.orden_de_compra'),
        ),
    ]
