# Generated by Django 4.2.1 on 2023-06-26 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0015_alter_gramajes_cantidad'),
        ('compras', '0019_alter_recepcion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcion',
            name='materias_primas',
        ),
        migrations.AddField(
            model_name='recepcion',
            name='cantidad_recepcion',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='materia_prima',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.materia_prima'),
        ),
        migrations.DeleteModel(
            name='OcRecepcion',
        ),
    ]
