# Generated by Django 4.2.1 on 2023-06-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=10)),
                ('giro', models.CharField(max_length=90)),
                ('pais', models.CharField(max_length=45)),
                ('region', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=45)),
                ('comuna', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=90)),
                ('condicion_de_pago', models.IntegerField(max_length=3)),
                ('nombre_contacto_1', models.CharField(max_length=45)),
                ('email_contacto_1', models.CharField(max_length=45)),
                ('telefono_contacto_1', models.CharField(max_length=15, null=True)),
                ('cargo_contacto_1', models.CharField(max_length=45, null=True)),
                ('nombre_contacto_2', models.CharField(max_length=45, null=True)),
                ('email_contacto_2', models.CharField(max_length=45, null=True)),
                ('telefono_contacto_2', models.CharField(max_length=15, null=True)),
                ('cargo_contacto_2', models.CharField(max_length=45, null=True)),
                ('info_adicional', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
