# Generated by Django 4.2.1 on 2023-06-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='condicion_de_pago',
        ),
    ]
